/** 业务错误码：按域分段，全量清单即 API 文档的一部分。 */
export const ERR = {
  // 通用
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  PERM_DENIED: "PERM_DENIED",
  RATE_LIMITED: "RATE_LIMITED",
  CONFLICT: "CONFLICT",
  INTERNAL: "INTERNAL",
  MAINTENANCE: "MAINTENANCE",

  // 认证账户 AUTH_*
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_SESSION_EXPIRED: "AUTH_SESSION_EXPIRED",
  AUTH_DISABLED: "AUTH_DISABLED",
  AUTH_PHONE_EXISTS: "AUTH_PHONE_EXISTS",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_SMS_CODE_INVALID: "AUTH_SMS_CODE_INVALID",
  AUTH_SMS_SEND_LIMIT: "AUTH_SMS_SEND_LIMIT",
  AUTH_WEAK_PASSWORD: "AUTH_WEAK_PASSWORD",
  AUTH_RESET_TOKEN_INVALID: "AUTH_RESET_TOKEN_INVALID",

  // 商品订单 CATALOG_/ORDER_*
  CATALOG_NOT_FOUND: "CATALOG_NOT_FOUND",
  CATALOG_INACTIVE: "CATALOG_INACTIVE",
  CATALOG_OUT_OF_STOCK: "CATALOG_OUT_OF_STOCK",
  CATALOG_OPTIONS_INVALID: "CATALOG_OPTIONS_INVALID",
  CATALOG_IDENTITY_REQUIRED: "CATALOG_IDENTITY_REQUIRED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_STATUS_INVALID: "ORDER_STATUS_INVALID",

  // 支付账务 PAY_/BILL_*
  PAY_GATEWAY_UNAVAILABLE: "PAY_GATEWAY_UNAVAILABLE",
  PAY_GATEWAY_ERROR: "PAY_GATEWAY_ERROR",
  PAY_SIGNATURE_INVALID: "PAY_SIGNATURE_INVALID",
  PAY_AMOUNT_MISMATCH: "PAY_AMOUNT_MISMATCH",
  PAY_INTENT_NOT_FOUND: "PAY_INTENT_NOT_FOUND",
  PAY_INTENT_EXPIRED: "PAY_INTENT_EXPIRED",
  BILL_INVOICE_NOT_FOUND: "BILL_INVOICE_NOT_FOUND",
  BILL_INVOICE_STATUS_INVALID: "BILL_INVOICE_STATUS_INVALID",
  BILL_INSUFFICIENT_BALANCE: "BILL_INSUFFICIENT_BALANCE",

  // 服务生命周期 SVC_*
  SVC_NOT_FOUND: "SVC_NOT_FOUND",
  SVC_STATUS_INVALID: "SVC_STATUS_INVALID",
  SVC_MODULE_ERROR: "SVC_MODULE_ERROR",
  SVC_MODULE_NOT_FOUND: "SVC_MODULE_NOT_FOUND",

  // 优惠 PROMO_*
  PROMO_INVALID: "PROMO_INVALID",
  PROMO_EXPIRED: "PROMO_EXPIRED",
  PROMO_LIMIT_REACHED: "PROMO_LIMIT_REACHED",
  PROMO_NOT_APPLICABLE: "PROMO_NOT_APPLICABLE",

  // 工单 TICKET_*
  TICKET_NOT_FOUND: "TICKET_NOT_FOUND",
  TICKET_CLOSED: "TICKET_CLOSED",
  TICKET_ATTACHMENT_INVALID: "TICKET_ATTACHMENT_INVALID",
} as const;

export type ErrorCode = (typeof ERR)[keyof typeof ERR];

export function isErrorCode(v: string): v is ErrorCode {
  return Object.prototype.hasOwnProperty.call(ERR, v);
}
